### ISSUE TITLE
throws exceptionl

### ISSUE THREAD

**Issue by psc0425** [jakkaj/HeatMargin#11]
here is the log file entry for the exception:

<entry>
    <record>1643</record>
    <time>2015/06/25 13:17:23.616</time>
    <type>Error</type>
    <source>Editor or Editor Extension</source>
    <description>System.ObjectDisposedException: Cannot access a disposed object.&#x000D;&#x000A;Object name: &apos;FormattedLine&apos;.&#x000D;&#x000A;   at Microsoft.VisualStudio.Text.Formatting.Implementation.FormattedLine.ThrowIfInvalid()&#x000D;&#x000A;   at Microsoft.VisualStudio.Text.Formatting.Implementation.FormattedLine.get_Start()&#x000D;&#x000A;   at HeatMarginExtension.View.HeatMarginViewModel._updateViewModelScroller(HeatMarginItemViewModel vm, ITextViewLine line)&#x000D;&#x000A;   at HeatMarginExtension.View.HeatMarginViewModel._doViewModel(LineWrapper line)&#x000D;&#x000A;   at HeatMarginExtension.View.HeatMarginViewModel.RefreshLines()&#x000D;&#x000A;   at HeatMarginExtension.HeatMarginExtension._textView_LayoutChanged(Object sender, TextViewLayoutChangedEventArgs e)&#x000D;&#x000A;   at Microsoft.VisualStudio.Text.Utilities.GuardedOperations.RaiseEvent[TArgs](Object sender, EventHandler`1 eventHandlers, TArgs args)</description>
  </entry>

**Comment by jakkaj** [comment]
Okay great thanks. Will have a look!

Sent from Outlook

On Thu, Jun 25, 2015 at 6:20 AM -0700, "psc0425" notifications@github.com wrote:

here is the log file entry for the exception:

```
1643

2015/06/25 13:17:23.616

Error

Editor or Editor Extension

System.ObjectDisposedException: Cannot access a disposed object.
```

Object name: 'FormattedLine'.
   at Microsoft.VisualStudio.Text.Formatting.Implementation.FormattedLine.ThrowIfInvalid()
   at Microsoft.VisualStudio.Text.Formatting.Implementation.FormattedLine.get_Start()
   at HeatMarginExtension.View.HeatMarginViewModel._updateViewModelScroller(HeatMarginItemViewModel vm, ITextViewLine line)
   at HeatMarginExtension.View.HeatMarginViewModel._doViewModel(LineWrapper line)
   at HeatMarginExtension.View.HeatMarginViewModel.RefreshLines()
   at HeatMarginExtension.HeatMarginExtension._textView_LayoutChanged(Object sender, TextViewLayoutChangedEventArgs e)
   at Microsoft.VisualStudio.Text.Utilities.GuardedOperations.RaiseEventTArgs

**Comment by jakkaj** [comment]
Closing as old, no crashes seen in a while
