### ISSUE TITLE
Heat Margin Edit Display

### ISSUE THREAD

**Issue by dirkstrauss** [jakkaj/HeatMargin#13]
Heat Margin no longer displays where I've edited after the 31 December 2016 update. I had it set to auto-update. I have to say, now that its no longer there, I realize just how much of a productivity tool this really is. I'm truly lost without it. 

Is there a setting I need to re-enable? I'm on Visual Studio Enterprise 2015 Update 3.

**Comment by jakkaj** [comment]
Hrm - interesting. It's been upgraded to the new VS2017 format. I wonder if it's not backwards compatible :/ 

For me - I noted that it was installed but not enabled in the features, could you please check that?

I could pop the old VSIX somewhere if you like.

**Comment by dirkstrauss** [comment]
I'll be using VS2017 as soon as it releases, so I'll just use that then. Thanks.

**Comment by AndersBillLinden** [comment]
It does not display in my vs 2015

**Comment by AndersBillLinden** [comment]
Seems to show up in yellow in my VS2015!

**Comment by jakkaj** [comment]
Yellow! Seems like an undocumented feature if ever i saw one! Can you post a screen shot?

I'm thinking we won't support older versions, but you could consider manually installing an older release from outside the marketplace if it's an issue. Not that I've properly done releases in GitHub it seems... I could pull one out I guess if you like.

**Comment by AndersBillLinden** [comment]
Oh, I was mistaken.

**Comment by jakkaj** [comment]
👍
